<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Events\Commands\" />
    <Folder Include="UseCases\AuditLogs\" />
    <Folder Include="UseCases\Reservations\Queries\" />
    <Folder Include="UseCases\Seats\Commands\" />
    <Folder Include="UseCases\Seats\Handlers\" />
    <Folder Include="UseCases\Seats\Queries\" />
    <Folder Include="UseCases\Sectors\Commands\" />
    <Folder Include="UseCases\Sectors\Handlers\" />
    <Folder Include="UseCases\Sectors\Queries\" />
    <Folder Include="UseCases\Users\Commands\" />
    <Folder Include="UseCases\Users\Handlers\" />
    <Folder Include="UseCases\Users\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
